services:
  app:
    build: .
    volumes:
      - app_data:/app/data
    environment:
      GIPHY_API_KEY: ${GIPHY_API_KEY}
      APP_DOMAIN: ${APP_DOMAIN:-localhost:8000}
      MERCURE_HOST: ${MERCURE_HOST:-http://mercure:80/.well-known/mercure}
      MERCURE_HOST_FRONTEND: ${MERCURE_HOST_FRONTEND:-http://localhost:3000/.well-known/mercure}
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY:-!ChangeThisMercureHubJWTSecretKey!}
    ports:
      - "${APP_PORT:-8000}:8000"

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    env_file: .env
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_EXTRA_DIRECTIVES: "cors_origins ${APP_URL:-http://localhost:8000}"
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - '${MERCURE_PORT:-3000}:80'
    volumes:
      - mercure_data:/data
      - mercure_config:/config

volumes:
  app_data:
  mercure_data:
  mercure_config: