services:
  app:
    build: .
    volumes:
      - data:/app/data
    environment:
      GIPHY_API_KEY: ${GIPHY_API_KEY}
      WEBSOCKET_HOST: ${WEBSOCKET_HOST:-ws://localhost:8000}
    ports:
      - "${PORT:-8000}:8000"

volumes:
  data: