services:
  app:
    build: .
    volumes:
      - ./data:/app/data
    environment:
      HOST: ${HOST:-localhost:8000}
      GIPHY_API_KEY: ${GIPHY_API_KEY}
      WEBSOCKET_PROTOCOL: ${WEBSOCKET_PROTOCOL:-ws}
    ports:
      - "${PORT:-8000}:8000"